using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using quotable.core;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace quotable.api.Controllers
{
    /// <summary>
    /// This is the resource that returns random quotes
    /// </summary>
    [Route("api/[controller]")]
    public class RandomController : Controller
    {
        /// <summary>
        /// This is the quote provider object from the core
        /// </summary>
        public SimpleRandomQuoteProvider randomQuoteProvider;

        /// <summary>
        /// This is the file path to the .txt file with quotes
        /// </summary>
        public string path;

        /// <summary>
        /// This constructor sets the file path of the .txt file
        /// </summary>
        public RandomController()
        {
            path = Constants.RemoteFilePath;
        }
        // GET: api/<controller>
        /// <summary>
        /// Gets a random quote from the .txt directory
        /// </summary>
        /// <returns>A random quote</returns>
        [HttpGet]
        public ActionResult<Quotes> Get()
        {
            randomQuoteProvider = new SimpleRandomQuoteProvider(path);
            int numberOfQuotes = randomQuoteProvider.getQuotes().Count();
            Random random = new Random();
            int rand = random.Next(0, numberOfQuotes);

            return randomQuoteProvider.getQuotesbyID(rand);
        }

        /// <summary>
        /// Autogenerated get method
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET api/<controller>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        /// <summary>
        /// Autogenerated post method
        /// </summary>
        /// <param name="value"></param>
        // POST api/<controller>
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }
        /// <summary>
        /// Autogenerated Put method
        /// </summary>
        /// <param name="id"></param>
        /// <param name="value"></param>

        // PUT api/<controller>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        /// <summary>
        /// Autogenerated Delete method
        /// </summary>
        /// <param name="id"></param>
        // DELETE api/<controller>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
